// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUstbM0JOQ3a7YFWLxfE68g9mAzfPLDpI',
    appId: '1:356717734416:web:0609af06e5baf24d3db895',
    messagingSenderId: '356717734416',
    projectId: 'ditonton-app-4a95b',
    authDomain: 'ditonton-app-4a95b.firebaseapp.com',
    storageBucket: 'ditonton-app-4a95b.appspot.com',
    measurementId: 'G-5HR6PQN2SH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBE0782gI3TNs_0Xdq5XrBKPPPyTDyq5Q',
    appId: '1:356717734416:android:6fec8d397f6b2b0a3db895',
    messagingSenderId: '356717734416',
    projectId: 'ditonton-app-4a95b',
    storageBucket: 'ditonton-app-4a95b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCAgdTy_ubjUmCt_VvNl5hpMF8axOeCL8',
    appId: '1:356717734416:ios:dc66178b8bbcf10a3db895',
    messagingSenderId: '356717734416',
    projectId: 'ditonton-app-4a95b',
    storageBucket: 'ditonton-app-4a95b.appspot.com',
    iosClientId: '356717734416-ndebvqntti97ltmmkj7vl9a0mtou7tsc.apps.googleusercontent.com',
    iosBundleId: 'com.dicoding.ditonton',
  );
}
