// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWxPTZxAgdA1uWGmDAhDh7SNyc1whDezk',
    appId: '1:589094164935:web:2229520c7a524c6d2d61e2',
    messagingSenderId: '589094164935',
    projectId: 'ditonton-app-a60fd',
    authDomain: 'ditonton-app-a60fd.firebaseapp.com',
    storageBucket: 'ditonton-app-a60fd.appspot.com',
    measurementId: 'G-4LHGZB9L6G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOm0dv3m4qEcQvozTXFirE4sHHwVg8Rbk',
    appId: '1:589094164935:android:5d5b0b2576476ea52d61e2',
    messagingSenderId: '589094164935',
    projectId: 'ditonton-app-a60fd',
    storageBucket: 'ditonton-app-a60fd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUFn8-x1Gn-O1FoETjdwDGr6u57ijxGYE',
    appId: '1:589094164935:ios:8a3d880859bbb09b2d61e2',
    messagingSenderId: '589094164935',
    projectId: 'ditonton-app-a60fd',
    storageBucket: 'ditonton-app-a60fd.appspot.com',
    iosClientId: '589094164935-kal8b1fs3jhoistu6rn4kruirqf1o92o.apps.googleusercontent.com',
    iosBundleId: 'com.dicoding.ditonton',
  );
}
